apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: ${ECR_REGISTRY}/backend:${IMAGE_TAG}
          ports:
            - containerPort: 8080
          env:
            - name: DB_HOST
              valueFrom:
              secretKeyRef:
                name: db-secret
                key: host
            - name: DB_USER
              valueFrom:
              secretKeyRef:
                name: db-secret
                key: username
            - name: DB_PASSWORD
              valueFrom:
              secretKeyRef:
                name: db-secret
                key: password
          resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
          requests:
            memory: "256Mi"
            cpu: "250m"
